from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ReversibilityClass(str, Enum):
    FULLY_REVERSIBLE = "fully_reversible"
    REVERSIBLE_WITH_EFFORT = "reversible_with_effort"
    PARTIALLY_REVERSIBLE = "partially_reversible"
    IRREVERSIBLE = "irreversible"
    CATASTROPHICALLY_IRREVERSIBLE = "catastrophically_irreversible"
    LEGALLY_IRREVERSIBLE = "legally_irreversible"


class FinancialImpact(str, Enum):
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class LegalImpact(str, Enum):
    NONE = "none"
    ADVISORY = "advisory"
    BINDING = "binding"
    REGULATORY = "regulatory"


class BlastRadiusScope(str, Enum):
    SINGLE_RECORD = "single_record"
    DEPARTMENT = "department"
    ORG = "org"
    EXTERNAL = "external"


class GuardrailClass(int, Enum):
    HARD_PROHIBITION = 1
    JURISDICTION_CONDITIONAL = 2
    MANDATORY_HUMAN_GATE = 3


@dataclass(frozen=True)
class RiskWeight:
    financial: int      # 0-10
    reversibility: int  # 0-10
    blast_radius: int   # 0-10

    @property
    def total(self) -> int:
        return self.financial + self.reversibility + self.blast_radius


@dataclass(frozen=True)
class CeilingRule:
    threshold_mwk: int | None = None
    threshold_percent: int | None = None
    threshold_percent_of_stock: int | None = None
    threshold_absolute_units: int | None = None
    price_change_percent: int | None = None
    bank_details_change: bool = False
    above_threshold_requires_gate: bool = True
    same_session_only: bool = False
    before_session_close: bool = False


@dataclass(frozen=True)
class EventContract:
    event_name: str
    module: str
    reversibility_class: ReversibilityClass
    financial_impact: FinancialImpact
    legal_impact: LegalImpact
    blast_radius_scope: BlastRadiusScope
    requires_human_gate: bool
    guardrail_class: GuardrailClass | None
    approval_capability: str | None
    jurisdiction_flags: tuple[str, ...]
    cascade_contribution: bool
    risk_weight: RiskWeight
    ceiling_rule: CeilingRule | None = None


EVENT_REGISTRY: dict[str, EventContract] = {
    "pos.session.open": EventContract(
        event_name="pos.session.open",
        module="pos",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 0),
    ),
    "pos.session.close": EventContract(
        event_name="pos.session.close",
        module="pos",
        reversibility_class=ReversibilityClass.PARTIALLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=("MW",),
        cascade_contribution=False,
        risk_weight=RiskWeight(2, 3, 1),
    ),
    "pos.transaction.execute": EventContract(
        event_name="pos.transaction.execute",
        module="pos",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:pos:approve:transaction",
        jurisdiction_flags=("MW",),
        cascade_contribution=True,
        risk_weight=RiskWeight(5, 4, 1),
        ceiling_rule=CeilingRule(threshold_mwk=500000),
    ),
    "pos.transaction.void": EventContract(
        event_name="pos.transaction.void",
        module="pos",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=("MW",),
        cascade_contribution=True,
        risk_weight=RiskWeight(2, 1, 1),
        ceiling_rule=CeilingRule(same_session_only=True, before_session_close=True),
    ),
    "pos.refund.execute": EventContract(
        event_name="pos.refund.execute",
        module="pos",
        reversibility_class=ReversibilityClass.IRREVERSIBLE,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:pos:approve:refund",
        jurisdiction_flags=("MW",),
        cascade_contribution=True,
        risk_weight=RiskWeight(6, 7, 2),
    ),
    "pos.discount.apply": EventContract(
        event_name="pos.discount.apply",
        module="pos",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:pos:approve:discount",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(3, 1, 1),
        ceiling_rule=CeilingRule(threshold_percent=20),
    ),
    "pos.price.override": EventContract(
        event_name="pos.price.override",
        module="pos",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:pos:approve:price-override",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(5, 2, 1),
    ),
    "pos.cash.drawer.open": EventContract(
        event_name="pos.cash.drawer.open",
        module="pos",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(1, 0, 0),
    ),
    "pos.product.lookup": EventContract(
        event_name="pos.product.lookup",
        module="pos",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 0),
    ),
    "inventory.stock.movement.record": EventContract(
        event_name="inventory.stock.movement.record",
        module="inventory",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(4, 4, 1),
    ),
    "inventory.stock.adjust": EventContract(
        event_name="inventory.stock.adjust",
        module="inventory",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:inventory:approve:adjustment",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(5, 5, 2),
        ceiling_rule=CeilingRule(
            threshold_percent_of_stock=5,
            threshold_absolute_units=50,
        ),
    ),
    "inventory.stock.write_off": EventContract(
        event_name="inventory.stock.write_off",
        module="inventory",
        reversibility_class=ReversibilityClass.IRREVERSIBLE,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:inventory:approve:write-off",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(7, 8, 4),
    ),
    "inventory.product.create": EventContract(
        event_name="inventory.product.create",
        module="inventory",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=("MW",),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 1, 0),
    ),
    "inventory.product.update": EventContract(
        event_name="inventory.product.update",
        module="inventory",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:inventory:approve:price-change",
        jurisdiction_flags=("MW",),
        cascade_contribution=False,
        risk_weight=RiskWeight(3, 2, 1),
        ceiling_rule=CeilingRule(price_change_percent=20),
    ),
    "inventory.stock.threshold.breach": EventContract(
        event_name="inventory.stock.threshold.breach",
        module="inventory",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(0, 0, 0),
    ),
    "inventory.stock.transfer": EventContract(
        event_name="inventory.stock.transfer",
        module="inventory",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:inventory:approve:transfer",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(3, 4, 3),
        ceiling_rule=CeilingRule(threshold_absolute_units=100),
    ),
    "inventory.supplier.update": EventContract(
        event_name="inventory.supplier.update",
        module="inventory",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:inventory:approve:supplier-update",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(4, 2, 2),
        ceiling_rule=CeilingRule(bank_details_change=True),
    ),
    "inventory.valuation.run": EventContract(
        event_name="inventory.valuation.run",
        module="inventory",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(2, 1, 5),
    ),
    "billing.capability.grant": EventContract(
        event_name="billing.capability.grant",
        module="billing",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:billing:capability:grant",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(8, 6, 8),
    ),
    "billing.capability.revoke": EventContract(
        event_name="billing.capability.revoke",
        module="billing",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:billing:capability:revoke",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(8, 6, 8),
    ),
    # --- Finance ---
    "finance.transfer.execute": EventContract(
        event_name="finance.transfer.execute",
        module="finance",
        reversibility_class=ReversibilityClass.IRREVERSIBLE,
        financial_impact=FinancialImpact.CRITICAL,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.EXTERNAL,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:transfer",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=True,
        risk_weight=RiskWeight(10, 10, 8),
        ceiling_rule=CeilingRule(threshold_mwk=500000),
    ),
    "finance.journal.create": EventContract(
        event_name="finance.journal.create",
        module="finance",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(3, 2, 1),
    ),
    "finance.journal.post": EventContract(
        event_name="finance.journal.post",
        module="finance",
        reversibility_class=ReversibilityClass.PARTIALLY_REVERSIBLE,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:journal-post",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(7, 6, 4),
    ),
    "finance.invoice.create": EventContract(
        event_name="finance.invoice.create",
        module="finance",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=("MW",),
        cascade_contribution=False,
        risk_weight=RiskWeight(3, 1, 1),
    ),
    "finance.invoice.send": EventContract(
        event_name="finance.invoice.send",
        module="finance",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.EXTERNAL,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:invoice-send",
        jurisdiction_flags=("MW",),
        cascade_contribution=False,
        risk_weight=RiskWeight(5, 6, 3),
    ),
    "finance.invoice.void": EventContract(
        event_name="finance.invoice.void",
        module="finance",
        reversibility_class=ReversibilityClass.PARTIALLY_REVERSIBLE,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:invoice-void",
        jurisdiction_flags=("MW",),
        cascade_contribution=True,
        risk_weight=RiskWeight(5, 6, 2),
    ),
    "finance.payment.record": EventContract(
        event_name="finance.payment.record",
        module="finance",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:payment",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(7, 6, 2),
        ceiling_rule=CeilingRule(threshold_mwk=1000000),
    ),
    "finance.budget.set": EventContract(
        event_name="finance.budget.set",
        module="finance",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:budget",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(7, 2, 7),
    ),
    "finance.record.delete": EventContract(
        event_name="finance.record.delete",
        module="finance",
        reversibility_class=ReversibilityClass.CATASTROPHICALLY_IRREVERSIBLE,
        financial_impact=FinancialImpact.CRITICAL,
        legal_impact=LegalImpact.REGULATORY,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.JURISDICTION_CONDITIONAL,
        approval_capability="erp:finance:approve:record-delete",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=False,
        risk_weight=RiskWeight(10, 10, 10),
    ),
    "finance.account.reconcile": EventContract(
        event_name="finance.account.reconcile",
        module="finance",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:finance:approve:reconcile",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(6, 5, 4),
    ),
    # --- Payroll ---
    "payroll.run.prepare": EventContract(
        event_name="payroll.run.prepare",
        module="payroll",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 2),
    ),
    "payroll.run.execute": EventContract(
        event_name="payroll.run.execute",
        module="payroll",
        reversibility_class=ReversibilityClass.IRREVERSIBLE,
        financial_impact=FinancialImpact.CRITICAL,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:payroll:approve",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=True,
        risk_weight=RiskWeight(10, 9, 9),
    ),
    "payroll.run.void": EventContract(
        event_name="payroll.run.void",
        module="payroll",
        reversibility_class=ReversibilityClass.PARTIALLY_REVERSIBLE,
        financial_impact=FinancialImpact.CRITICAL,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.ORG,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:payroll:approve:void",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=True,
        risk_weight=RiskWeight(10, 9, 9),
    ),
    "payroll.deduction.add": EventContract(
        event_name="payroll.deduction.add",
        module="payroll",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.MEDIUM,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:payroll:approve:deduction",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(5, 5, 1),
        ceiling_rule=CeilingRule(threshold_percent=30),
    ),
    "payroll.payslip.generate": EventContract(
        event_name="payroll.payslip.generate",
        module="payroll",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 3),
    ),
    "payroll.tax.calculate": EventContract(
        event_name="payroll.tax.calculate",
        module="payroll",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.REGULATORY,
        blast_radius_scope=BlastRadiusScope.DEPARTMENT,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 3),
    ),
    # --- HR ---
    "hr.employee.create": EventContract(
        event_name="hr.employee.create",
        module="hr",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:hr:approve:employment",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=True,
        risk_weight=RiskWeight(7, 6, 1),
    ),
    "hr.employee.terminate": EventContract(
        event_name="hr.employee.terminate",
        module="hr",
        reversibility_class=ReversibilityClass.LEGALLY_IRREVERSIBLE,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:hr:approve:employment",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=True,
        risk_weight=RiskWeight(8, 10, 2),
    ),
    "hr.employee.update": EventContract(
        event_name="hr.employee.update",
        module="hr",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:hr:approve:employment",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(2, 1, 1),
        ceiling_rule=CeilingRule(bank_details_change=True),
    ),
    "hr.salary.change": EventContract(
        event_name="hr.salary.change",
        module="hr",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:hr:approve:employment",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(8, 6, 1),
    ),
    "hr.contract.issue": EventContract(
        event_name="hr.contract.issue",
        module="hr",
        reversibility_class=ReversibilityClass.LEGALLY_IRREVERSIBLE,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:hr:approve:employment",
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=False,
        risk_weight=RiskWeight(7, 9, 1),
    ),
    "hr.leave.approve": EventContract(
        event_name="hr.leave.approve",
        module="hr",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.LOW,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.MANDATORY_HUMAN_GATE,
        approval_capability="erp:hr:approve:leave",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(2, 3, 1),
    ),
    "hr.compliance.flag": EventContract(
        event_name="hr.compliance.flag",
        module="hr",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=("MW", "ZA", "KE"),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 1),
    ),
    # --- CRM ---
    "crm.contract.draft": EventContract(
        event_name="crm.contract.draft",
        module="crm",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 1),
    ),
    "crm.contract.send": EventContract(
        event_name="crm.contract.send",
        module="crm",
        reversibility_class=ReversibilityClass.LEGALLY_IRREVERSIBLE,
        financial_impact=FinancialImpact.HIGH,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.EXTERNAL,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:crm:approve:contract",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(7, 9, 3),
    ),
    "crm.contract.sign": EventContract(
        event_name="crm.contract.sign",
        module="crm",
        reversibility_class=ReversibilityClass.LEGALLY_IRREVERSIBLE,
        financial_impact=FinancialImpact.CRITICAL,
        legal_impact=LegalImpact.BINDING,
        blast_radius_scope=BlastRadiusScope.EXTERNAL,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:crm:approve:contract",
        jurisdiction_flags=(),
        cascade_contribution=True,
        risk_weight=RiskWeight(9, 10, 4),
    ),
    "crm.opportunity.update": EventContract(
        event_name="crm.opportunity.update",
        module="crm",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 0, 1),
    ),
    "crm.client.create": EventContract(
        event_name="crm.client.create",
        module="crm",
        reversibility_class=ReversibilityClass.FULLY_REVERSIBLE,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.NONE,
        blast_radius_scope=BlastRadiusScope.SINGLE_RECORD,
        requires_human_gate=False,
        guardrail_class=None,
        approval_capability=None,
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 1, 1),
    ),
    "crm.communication.send": EventContract(
        event_name="crm.communication.send",
        module="crm",
        reversibility_class=ReversibilityClass.REVERSIBLE_WITH_EFFORT,
        financial_impact=FinancialImpact.NONE,
        legal_impact=LegalImpact.ADVISORY,
        blast_radius_scope=BlastRadiusScope.EXTERNAL,
        requires_human_gate=True,
        guardrail_class=GuardrailClass.HARD_PROHIBITION,
        approval_capability="erp:crm:approve:communication",
        jurisdiction_flags=(),
        cascade_contribution=False,
        risk_weight=RiskWeight(0, 5, 3),
    ),
}

HARD_PROHIBITED_FOR_AGENTS: frozenset[str] = frozenset([
    "billing.capability.grant",
    "billing.capability.revoke",
    "billing.subscription.activate",
    "billing.subscription.suspend",
    "billing.subscription.cancel",
    "finance.record.delete",
    "hr.employee.terminate",
    "hr.contract.issue",
    "crm.contract.send",
    "crm.contract.sign",
    "crm.communication.send",
    # payroll.run.execute: agents may propose payroll; human gate handles approval
])

CASCADE_RISK_BUDGET_DEFAULT = 30
CASCADE_DEPTH_MAX = 3
BLAST_RADIUS_RECORD_THRESHOLD = 0.10  # 10% of org records
