[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@10",
  "echo '//npm.pkg.github.com/:_authToken='$GITHUB_TOKEN >> .npmrc",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["echo 'no build'"]

[start]
cmd = "node apps/server/dev.mjs"
