"""Add terminal_device_id

Revision ID: 0a5d343d30bb
Revises: c20d1a5dfbe0
Create Date: 2026-03-29 18:44:10.854015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5d343d30bb'
down_revision: Union[str, None] = 'c20d1a5dfbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
