"""add fiscal_provider to tenants

Revision ID: 1d4d514e8dc5
Revises: ece59b72a863
Create Date: 2026-03-31 06:07:53.024054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d4d514e8dc5'
down_revision: Union[str, None] = 'ece59b72a863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('fiscal_provider', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('fiscal_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'fiscal_config')
    op.drop_column('tenants', 'fiscal_provider')
    # ### end Alembic commands ###
