"""Add missing tenant_id columns to role_atoms, sale_lines, etc

Revision ID: 9a635ecf13a7
Revises: 3e1420710932
Create Date: 2026-04-05 14:17:48.335056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a635ecf13a7'
down_revision: Union[str, None] = '3e1420710932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear out dangling rows to satisfy NOT NULL constraints on new tenant_id columns
    op.execute("TRUNCATE table kitchen_order_lines, payments, role_atoms, sale_lines, tab_lines CASCADE;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitchen_order_lines', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'kitchen_order_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('password_reset_tokens', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'password_reset_tokens', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('role_atoms', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'role_atoms', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('sale_lines', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'sale_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('tab_lines', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'tab_lines', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tab_lines', type_='foreignkey')
    op.drop_column('tab_lines', 'tenant_id')
    op.drop_constraint(None, 'sale_lines', type_='foreignkey')
    op.drop_column('sale_lines', 'tenant_id')
    op.drop_constraint(None, 'role_atoms', type_='foreignkey')
    op.drop_column('role_atoms', 'tenant_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'tenant_id')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_column('password_reset_tokens', 'tenant_id')
    op.drop_constraint(None, 'kitchen_order_lines', type_='foreignkey')
    op.drop_column('kitchen_order_lines', 'tenant_id')
    # ### end Alembic commands ###
