"""add terminal_device_id to tenants

Revision ID: c20d1a5dfbe0
Revises: c9edeb34f5a9
Create Date: 2026-03-29 18:23:43.887378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c20d1a5dfbe0'
down_revision: Union[str, None] = 'c9edeb34f5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_table('stock_take_counts')
    op.drop_table('stock_take_sessions')
    op.drop_table('media')
    op.drop_table('push_tokens')
    op.drop_index('idx_constitutional_audit_log_hash', table_name='constitutional_audit_log')
    op.drop_index('idx_constitutional_audit_log_org_logged', table_name='constitutional_audit_log')
    op.drop_index('idx_constitutional_audit_log_outcome', table_name='constitutional_audit_log')
    op.drop_index('idx_constitutional_audit_log_workflow', table_name='constitutional_audit_log')
    op.drop_table('constitutional_audit_log')
    op.drop_index('ix_audit_log_tenant_id', table_name='audit_log')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_auth_tokens_token', table_name='auth_tokens')
    op.drop_index('ix_auth_tokens_user_id', table_name='auth_tokens')
    op.drop_index('ix_cash_sessions_tenant_id', table_name='cash_sessions')
    op.drop_index('ix_categories_tenant_id', table_name='categories')
    op.drop_index('ix_customers_tenant_id', table_name='customers')
    op.alter_column('org_invites', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_payments_sale_id', table_name='payments')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.create_unique_constraint('uq_product_tenant_sku', 'products', ['tenant_id', 'sku'])
    op.drop_index('ix_sale_lines_sale_id', table_name='sale_lines')
    op.drop_index('ix_sales_sale_number', table_name='sales')
    op.drop_index('ix_sales_tenant_id', table_name='sales')
    op.drop_constraint('sales_sale_number_key', 'sales', type_='unique')
    op.create_unique_constraint('uq_sale_tenant_number', 'sales', ['tenant_id', 'sale_number'])
    op.drop_index('ix_stock_movements_product_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_id', table_name='stock_movements')
    op.add_column('tenants', sa.Column('terminal_device_id', sa.String(), nullable=True))
    op.drop_index('ix_user_tenants_tenant_id', table_name='user_tenants')
    op.drop_index('ix_user_tenants_user_id', table_name='user_tenants')
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_tenant_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'account_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index('ix_user_tenants_user_id', 'user_tenants', ['user_id'], unique=False)
    op.create_index('ix_user_tenants_tenant_id', 'user_tenants', ['tenant_id'], unique=False)
    op.drop_column('tenants', 'terminal_device_id')
    op.create_index('ix_stock_movements_tenant_id', 'stock_movements', ['tenant_id'], unique=False)
    op.create_index('ix_stock_movements_product_id', 'stock_movements', ['product_id'], unique=False)
    op.drop_constraint('uq_sale_tenant_number', 'sales', type_='unique')
    op.create_unique_constraint('sales_sale_number_key', 'sales', ['sale_number'])
    op.create_index('ix_sales_tenant_id', 'sales', ['tenant_id'], unique=False)
    op.create_index('ix_sales_sale_number', 'sales', ['sale_number'], unique=False)
    op.create_index('ix_sale_lines_sale_id', 'sale_lines', ['sale_id'], unique=False)
    op.drop_constraint('uq_product_tenant_sku', 'products', type_='unique')
    op.create_index('ix_products_tenant_id', 'products', ['tenant_id'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_payments_sale_id', 'payments', ['sale_id'], unique=False)
    op.alter_column('org_invites', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index('ix_customers_tenant_id', 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_categories_tenant_id', 'categories', ['tenant_id'], unique=False)
    op.create_index('ix_cash_sessions_tenant_id', 'cash_sessions', ['tenant_id'], unique=False)
    op.create_index('ix_auth_tokens_user_id', 'auth_tokens', ['user_id'], unique=False)
    op.create_index('ix_auth_tokens_token', 'auth_tokens', ['token'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_log_tenant_id', 'audit_log', ['tenant_id'], unique=False)
    op.create_table('constitutional_audit_log',
    sa.Column('entry_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('previous_entry_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entry_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_context_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('causal_depth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cumulative_risk_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ip_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('capability_snapshot_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('delegation_chain', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'::uuid[]"), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('block_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approval_capability', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('guardrail_step_reached', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('logged_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('jurisdiction_scope', postgresql.ARRAY(sa.VARCHAR(length=8)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('payload_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('entry_id', name='constitutional_audit_log_pkey'),
    sa.UniqueConstraint('entry_hash', name='constitutional_audit_log_entry_hash_key')
    )
    op.create_index('idx_constitutional_audit_log_workflow', 'constitutional_audit_log', ['workflow_context_id', 'causal_depth'], unique=False)
    op.create_index('idx_constitutional_audit_log_outcome', 'constitutional_audit_log', ['org_id', 'outcome', sa.text('logged_at DESC')], unique=False)
    op.create_index('idx_constitutional_audit_log_org_logged', 'constitutional_audit_log', ['org_id', sa.text('logged_at DESC')], unique=False)
    op.create_index('idx_constitutional_audit_log_hash', 'constitutional_audit_log', ['entry_hash'], unique=False)
    op.create_table('push_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.CheckConstraint("platform::text = ANY (ARRAY['ios'::character varying, 'android'::character varying]::text[])", name='ck_push_tokens_platform'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='push_tokens_tenant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='push_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='push_tokens_pkey')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='media_tenant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='media_uploaded_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='media_pkey')
    )
    op.create_table('stock_take_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name='ck_sts_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='stock_take_sessions_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='stock_take_sessions_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_take_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('stock_take_counts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('counted_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('system_qty', sa.NUMERIC(precision=12, scale=3), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('counted_qty', sa.NUMERIC(precision=12, scale=3), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('variance', sa.NUMERIC(precision=12, scale=3), sa.Computed('(counted_qty - system_qty)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('flagged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], name='stock_take_counts_counted_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['stock_take_sessions.id'], name='stock_take_counts_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='stock_take_counts_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stock_take_counts_pkey')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('decision_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('decision_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])", name='ck_approvals_status'),
    sa.ForeignKeyConstraint(['decision_by'], ['users.id'], name='approvals_decision_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='approvals_requested_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='approvals_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='approvals_pkey')
    )
    # ### end Alembic commands ###
