"""fiscal_submissions table + product unspsc columns

Revision ID: ece59b72a863
Revises: 0a5d343d30bb
Create Date: 2026-03-31 05:20:24.107750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece59b72a863'
down_revision: Union[str, None] = '0a5d343d30bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_submissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sale_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('fiscal_code', sa.String(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('receipt_block', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('unspsc_code', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('fiscal_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fiscal_codes')
    op.drop_column('products', 'unspsc_code')
    op.drop_table('fiscal_submissions')
    # ### end Alembic commands ###
